// Final page functionality
let finalPostContent = '';
let generatedImageUrl = '';

// Load final post and image
function loadFinalContent() {
    // Load post content
    finalPostContent = localStorage.getItem('finalPost') || localStorage.getItem('generatedPost');
    
    if (!finalPostContent) {
        window.location.href = 'generate.html';
        return;
    }
    
    // Display post content
    document.getElementById('finalPostContent').innerHTML = finalPostContent;
    
    // Load generated image
    generatedImageUrl = localStorage.getItem('generatedImageUrl');
    const imageContainer = document.getElementById('imageContainer');
    
    console.log('Loading final content. Image URL:', generatedImageUrl);
    console.log('Image URL type:', typeof generatedImageUrl);
    console.log('Image URL length:', generatedImageUrl ? generatedImageUrl.length : 0);
    
    if (generatedImageUrl && generatedImageUrl.trim() !== '' && generatedImageUrl !== 'null' && generatedImageUrl !== 'undefined') {
        const img = document.createElement('img');
        img.src = generatedImageUrl;
        img.alt = 'Generated AI Image';
        img.className = 'generated-image';
        
        img.onerror = function() {
            console.error('Failed to load image from URL:', generatedImageUrl);
            imageContainer.innerHTML = `
                <div class="image-error">
                    <p>⚠️ Failed to load generated image</p>
                    <p style="font-size: 12px; color: #666; margin-top: 8px;">Image URL: ${generatedImageUrl.substring(0, 50)}...</p>
                </div>
            `;
        };
        
        img.onload = function() {
            console.log('Image loaded successfully!');
        };
        
        imageContainer.innerHTML = '';
        imageContainer.appendChild(img);
    } else {
        // Create a sample image for testing (placeholder with downloadable content)
        const canvas = document.createElement('canvas');
        canvas.width = 400;
        canvas.height = 300;
        const ctx = canvas.getContext('2d');
        
        // Create a simple gradient background
        const gradient = ctx.createLinearGradient(0, 0, 400, 300);
        gradient.addColorStop(0, '#667eea');
        gradient.addColorStop(1, '#764ba2');
        ctx.fillStyle = gradient;
        ctx.fillRect(0, 0, 400, 300);
        
        // Add text
        ctx.fillStyle = 'white';
        ctx.font = 'bold 24px Arial';
        ctx.textAlign = 'center';
        ctx.fillText('Sample LinkedIn Post Image', 200, 120);
        ctx.font = '16px Arial';
        ctx.fillText('Generated by AI Post Generator', 200, 150);
        ctx.fillText('(DALL-E integration coming soon)', 200, 180);
        
        // Convert to data URL and display
        const dataUrl = canvas.toDataURL('image/png');
        imageContainer.innerHTML = `
            <img src="${dataUrl}" alt="Sample Generated Image" class="generated-image" />
        `;
        
        console.log('Created sample image for testing');
    }
}

// Copy post text to clipboard
async function copyPost() {
    try {
        // Strip HTML tags for plain text copy
        const textContent = finalPostContent.replace(/<[^>]*>/g, '').replace(/&nbsp;/g, ' ').replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&amp;/g, '&');
        
        await navigator.clipboard.writeText(textContent);
        
        // Show success feedback
        const btn = document.getElementById('copyPostBtn');
        const originalHTML = btn.innerHTML;
        btn.innerHTML = '<span class="action-icon">✓</span><span>Copied!</span>';
        btn.classList.add('success');
        
        setTimeout(() => {
            btn.innerHTML = originalHTML;
            btn.classList.remove('success');
        }, 2000);
        
        showNotification('Post text copied to clipboard!', 'success');
    } catch (error) {
        console.error('Failed to copy text:', error);
        showNotification('Failed to copy text. Please try again.', 'error');
    }
}

// Download generated image
async function downloadImage() {
    const btn = document.getElementById('downloadBtn');
    const originalHTML = btn.innerHTML;
    
    try {
        btn.innerHTML = '<span class="action-icon">⏳</span><span>Downloading...</span>';
        btn.disabled = true;
        
        // Check if we have a generated image URL
        if (generatedImageUrl && generatedImageUrl.trim() !== '') {
            console.log('Downloading generated image:', generatedImageUrl);
            
            // Fetch the generated image
            const response = await fetch(generatedImageUrl);
            if (!response.ok) throw new Error(`Failed to fetch image: ${response.status}`);
            
            const blob = await response.blob();
            downloadBlob(blob, `linkedin-post-image-${Date.now()}.png`);
            
        } else {
            // Try to download the displayed image (even if it's a placeholder)
            const imageElement = document.querySelector('.generated-image');
            
            if (imageElement && imageElement.src) {
                console.log('Downloading displayed image:', imageElement.src);
                
                // If it's a data URL or blob URL, download directly
                if (imageElement.src.startsWith('data:') || imageElement.src.startsWith('blob:')) {
                    const response = await fetch(imageElement.src);
                    const blob = await response.blob();
                    downloadBlob(blob, `linkedin-post-image-${Date.now()}.png`);
                } else {
                    // External URL - try to fetch with CORS
                    try {
                        const response = await fetch(imageElement.src, { mode: 'cors' });
                        if (!response.ok) throw new Error('CORS or network error');
                        const blob = await response.blob();
                        downloadBlob(blob, `linkedin-post-image-${Date.now()}.png`);
                    } catch (corsError) {
                        // Fallback: open image in new tab for manual download
                        window.open(imageElement.src, '_blank');
                        showNotification('Image opened in new tab for manual download', 'info');
                        return;
                    }
                }
            } else {
                throw new Error('No image available to download');
            }
        }
        
        // Show success feedback
        btn.innerHTML = '<span class="action-icon">✓</span><span>Downloaded!</span>';
        btn.classList.add('success');
        
        setTimeout(() => {
            btn.innerHTML = originalHTML;
            btn.classList.remove('success');
            btn.disabled = false;
        }, 2000);
        
        showNotification('Image downloaded successfully!', 'success');
        
    } catch (error) {
        console.error('Failed to download image:', error);
        showNotification(`Failed to download image: ${error.message}`, 'error');
        
        // Reset button
        btn.innerHTML = originalHTML;
        btn.disabled = false;
    }
}

// Helper function to download blob
function downloadBlob(blob, filename) {
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    window.URL.revokeObjectURL(url);
}

// Copy image URL to clipboard
async function copyImageUrl() {
    if (!generatedImageUrl) {
        showNotification('No image URL to copy. Image generation is not yet configured.', 'info');
        return;
    }
    
    try {
        await navigator.clipboard.writeText(generatedImageUrl);
        
        // Show success feedback
        const btn = document.getElementById('copyUrlBtn');
        const originalHTML = btn.innerHTML;
        btn.innerHTML = '<span class="action-icon">✓</span><span>Copied!</span>';
        btn.classList.add('success');
        
        setTimeout(() => {
            btn.innerHTML = originalHTML;
            btn.classList.remove('success');
        }, 2000);
        
        showNotification('Image URL copied to clipboard!', 'success');
    } catch (error) {
        console.error('Failed to copy URL:', error);
        showNotification('Failed to copy URL. Please try again.', 'error');
    }
}

// Create another post
function createAnother() {
    // Clear stored data
    localStorage.removeItem('postTopic');
    localStorage.removeItem('generatedPost');
    localStorage.removeItem('finalPost');
    localStorage.removeItem('imageQuote');
    localStorage.removeItem('generatedImageUrl');
    localStorage.removeItem('finalQuote');
    
    // Navigate to start
    window.location.href = 'generate.html';
}

// Check authentication
async function checkAuth() {
    const { data: { session } } = await supabase.auth.getSession();
    
    if (!session) {
        window.location.href = 'index.html';
    }
}

// Initialize page
document.addEventListener('DOMContentLoaded', () => {
    checkAuth();
    loadFinalContent();
});